### PR TITLE
fix: modify jq -cr to fix error in append_to_params

### LINKED ISSUE #55: Incorrect jq usage in append_string_to_params
Hey, super useful orb - thank you! We are hoping that `trigger-workflows-for-all-modified` will substantially speed up our CI and bring the cost down.

When using the above step, it fails with the following error: 
image

I copied the source of this into our pipeline and added `set -x` for debugging - it looks like `jq -cr` is the culprit. Trying this locally I got the same error and it seems that `jq -cr ''` is correct if you want to redirect the output to a file. I will put in a PR to fix this.

### PR DESCRIPTION
**Pull request by noisyscanner**
Fixes #55

### CODE REVIEW

**Comment by roopakv** [comment]
@noisyscanner i forgot to turn on build pull requests. could you push an empty commit to trigger runs please :)

**Comment by roopakv** [comment]
Works: https://app.circleci.com/pipelines/github/swissknife/circle-monorepo/79/workflows/f52bc523-0818-42c5-a087-8d14e8d6cd08/jobs/102

**Comment by noisyscanner** [comment]
Sweet thanks for merging quickly! Do you have an ETA for when you will be able to release the new version?

**Comment by roopakv** [comment]
@noisyscanner just released. check out orb.swissknife.dev

**Comment by noisyscanner** [comment]
thanks!

**Pull request merged**
